### ISSUE TITLE
Map not appearing

### ISSUE THREAD

**Issue by rissawyss** [geniusfund/odoo#4]
Map not appearing / greyed out. Here is the error:
<img width="1557" alt="Screen Shot 2019-04-22 at 11 15 20 AM" src="https://user-images.githubusercontent.com/22284225/56516679-f6acec80-64ef-11e9-8f37-e7a915ba2a7e.png">

Error:
Unknown CORS error

An unknown CORS error occured. The error probably originates from a JavaScript file served from a different origin. (Opening your browser console might give you a hint on the error.)

**Comment by sebastienriss** [comment]
HI Marrissa, I think I solved the problem but I have an issue with the API. I get this error : 

Unable to geolocate, received the error:
This API key is not authorized to use this service or API.

Google made this a paid feature.
You should first enable billing on your Google account.
Then, go to Developer Console, and enable the APIs:
Geocoding, Maps Static, Maps Javascript.

Could you please check on google side?

**Comment by rissawyss** [comment]
Hi Sebastien,
We solved the geolocate issue on our end. Now this is the error that is appearing (see image).

Thank you,
Marissa
<img width="1439" alt="Screen Shot 2019-04-24 at 12 10 58 PM" src="https://user-images.githubusercontent.com/22284225/56693367-1c292a00-6699-11e9-8984-ce09b404923b.png">

**Comment by rissawyss** [comment]
@sebastienriss This issue needs to be fixed - details have been provided by Odoo Support
<img width="740" alt="Screen Shot 2019-04-25 at 9 27 20 AM" src="https://user-images.githubusercontent.com/22284225/56752142-7c24dc80-673c-11e9-956c-471558ff2394.png">

**Comment by sebastienriss** [comment]
Ok, it's working now.

It was a problem with a code I created. I tried to update the map instantly when we change an information but I don't succeed for now. So, The map is refresh when you save the record.

**Comment by rissawyss** [comment]
OK - this is what I'm seeing. The "blue" part of the Google map. When I select a company, the map does not change.
<img width="1908" alt="Screen Shot 2019-04-25 at 12 16 18 PM" src="https://user-images.githubusercontent.com/22284225/56762215-3411b400-6754-11e9-8b87-866aba4ca9b5.png">

**Comment by sebastienriss** [comment]
You have to save it for update the map. I didn't find a way yet for now to
update it instantly.


Regards,
[image: Sébastien Riss]

*Sébastien Riss*
CEO
sebastien.riss@captivea.us <http:///>

*[image: linkedin] <https://www.linkedin.com/in/riss-sebastien/> [image:
twitter] <https://twitter.com/riss_sebastien> [image: google +]
<https://plus.google.com/u/0/+S%C3%A9bastienRiss>*

[image: captivea]

*CAPTIVEA*
www.captivea.us
(407) 392 2217

------------------------------

[image: white paper]



How to choose a business management software?

Download the guide now >> <https://goo.gl/agCSy5>

*BLOG*

www.captivea.us/blog

*Follow us:*

[image: linkedin] [image: twitter]
